version: "3.7"
services:
  backend:
    container_name: pdp_math
    image: pdp_math-app
    ports:
      - "8080:8080"
    healthcheck:
      interval: 5s
      retries: 10
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8080/hello/hello
