server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: quadratic-group-id
    topic: quadratic-formula-topic
  security:
    user:
      name: james
      password: $2a$12$yt6LNISxcm83rFBzz5itY.L.ENTxP7EaHCvpHyBZX4hq7vmlIkjDa
#springdoc:
#  swagger-ui:
#    oauth:
#      client-id: ${CLIENT_ID}
#      client-secret: ${CLIENT_SECRET}
