# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '3.7'
services:
  postgresql:
    pull_policy: always
    container_name: bitnami_postgresql
    image: docker.io/bitnami/postgresql:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  keycloak:
    pull_policy: always
    container_name: bitnami_keycloak
    image: docker.io/bitnami/keycloak:latest
    depends_on:
      - postgresql
    ports:
      - "8080:8080"

volumes:
  postgresql_data:
    driver: local